name: flutter_word_manager
description: A Flutter project to collect and manage words for crossword like games
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  equatable: ^2.0.3
  file_picker: ^3.0.4
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.9
  hive: ^2.2.3
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  rxdart: ^0.27.4
  syncfusion_flutter_charts: ^20.2.36
  uuid: ^3.0.6
  word_storage_api:
    path: "packages/word_storage_api"
  word_storage_repository:
    path: "packages/word_storage_repository"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
